### ISSUE TITLE
Wrong link in documentation

### ISSUE THREAD

**Issue by jbreuer95** [creativetimofficial/ct-vue-now-ui-dashboard-pro#12]
In the docs on:
https://demos.creative-tim.com/vue-now-ui-dashboard-pro/documentation/#/getting-started

The Github link in the right top directs too:
https://github.com/creativetimofficial/vue-light-bootstrap-dashboard-pro

Thats why i reported this [issue](https://github.com/creativetimofficial/ct-vue-light-bootstrap-dashboard-pro/issues/20) in the wrong thread. But i quess it applies there too :)

**Comment by cristijora** [comment]
We recently did an update and all the wrong links + some other improvements/bug fixes were made so this should no longer be an issue.
