### ISSUE TITLE
Navigation Pills - Horizontal Tabs Overflow

### ISSUE THREAD

**Issue by CoreAutomation-JD** [creativetimofficial/ct-vue-now-ui-dashboard-pro#13]
When you go into a mobile vertical layout, the tabs overflow on top of each other
![overflow](https://user-images.githubusercontent.com/19941828/40955482-5efea28c-6858-11e8-885d-ddd3417d2bee.png)

**Comment by cristijora** [comment]
This issue should no longer be present in the latest update. Now, tabs default to vertical layout on smaller screens.
To get the update, go to your accounts (Download section) and re-download the template, copy the `assets, components` and `vue.config.js` files. Also you could diff `package.json` to check what packages were upgraded.
