### ISSUE TITLE
Tabs component and v-model

### ISSUE THREAD

**Issue by vovek** [creativetimofficial/ct-vue-now-ui-dashboard-pro#16]
Hello!
I'm trying to use Tab component with v-model as described in [documentation](https://demos.creative-tim.com/vue-now-ui-dashboard-pro/documentation/#/tabs?id=control-with-v-model)
```javascript
<card no-footer-line class="subscriptions">
  <tabs v-model="activeTab" type="primary" vertical="" class="row">
    <tab-pane v-for="subscription in subscriptions.available" :key="subscription.tar_id" :label="subscription.name">
      <span slot="default">
        <el-form class="filter">
          <span class="price">
            {{ subscription.rent + ' ' + subscription.currency}}
          </span>
          <el-form-item v-for="option in subscription.options" :key="option.id" class="option">
            <span class="option-name">{{ option.descr }}</span>
            <el-slider v-model="selectedProduct.option" :min="option.minMul" :max="option.maxMul" class="option-slider"></el-slider>
          </el-form-item>
          <button class="btn btn-primary" @click.prevent="fetchOrders">{{ $t('Подключить') }}</button>
        </el-form>
      </span>
    </tab-pane>
  </tabs>
</card>
```
I have a state.activeTab property and it doesn't update value after clicking on tab.
```javascript
data () {
  return {
    activeTab: '',
    ...
  }
}
```

Am I doing wrong?
And one more question, can I use something different than "label" to track selected item?

Thanks for helping!

**Comment by vovek** [comment]
Or how can I add custom event to trigger clicking tab?

**Comment by cristijora** [comment]
This issue should no longer be present in the latest update. Added `v-model` support for Tabs which was missing.
To get the update, go to your accounts (Download section) and re-download the template, copy the `assets, components` and `vue.config.js` files. Also you could diff `package.json` to check what packages were upgraded.
