### ISSUE TITLE
Switch doesnt have color option

### ISSUE THREAD

**Issue by jbreuer95** [creativetimofficial/ct-vue-now-ui-dashboard-pro#17]
In the docs you can give a color to a switch but it is not represented in the code

**Comment by cristijora** [comment]
This issue should no longer be present in the latest update. Added missing `color class` configuration on switches which should allow colored switches now.
To get the update, go to your accounts (Download section) and re-download the template, copy the `assets, components` and `vue.config.js` files. Also you could diff `package.json` to check what packages were upgraded.
