### ISSUE TITLE
A couple of issues 

### ISSUE THREAD

**Issue by hilalh** [creativetimofficial/ct-vue-now-ui-dashboard-pro#19]
1. User section in the menu seems to have the photo hard coded rather than being built as a proper component that grabs information from the js portion of the UserMenu.vue file
2. yarn.lock is outdated and doesn't work with node 10.x
3. Hot-reload functionality is easily broken once using back button to navigate from a 404 page. It won't even show the latest build files. Please fix this. Thanks.

**Comment by decisao** [comment]
Hi,

Do you got any response from support? 

I have premium support but it does not work at all.

**Comment by cristijora** [comment]
These issue(s) should no longer be present in the latest update. We did some improvements, package updates & more and everything should now be up to date and working properly with latest Node.js version

To get the update, go to your accounts (Download section) and re-download the template, copy the `assets, components` and `vue.config.js` files. Also you could diff `package.json` to check what packages were upgraded.
