### ISSUE TITLE
Is this one also Vue?

### ISSUE THREAD

**Issue by e-stonia** [creativetimofficial/ct-vue-now-ui-dashboard-pro#20]
I bought a bundle as I wanted both Vue Now products (Kit and Dashboard) but on download page I noticed that every single item had 3 options: Vue, HTML and PSD/Sketch except this one - Vue Now Dashboard that has: HTML, HTML  and PSD/Sketch: https://i.imgur.com/EMl4YkI.png

Is it just a mistake and wrong button?

**Comment by cristijora** [comment]
Unfortunately this is a wrong button that we cannot fix but it should not appear on all the other products. I will close the issue as it's not relevant to the template itself.
