### ISSUE TITLE
Documentation link broken 

### ISSUE THREAD

**Issue by decisao** [creativetimofficial/ct-vue-now-ui-dashboard-pro#21]
Hello,

The documentation link is broken. How to access the documentation?

Elieser

**Comment by cristijora** [comment]
Sorry for the late reply here. We usually respond to custom support done via website and fix github issues when they add up to 8-10 issues.
Here's the link to documentation https://demos.creative-tim.com/vue-now-ui-dashboard-pro/documentation/#/getting-started

**Comment by cristijora** [comment]
Fixed all links documentation and readme in latest update.
To get the update, go to your accounts (Download section) and re-download the template, copy the `assets, components` and `vue.config.js` files. Also you could diff `package.json` to check what packages were upgraded.
