### ISSUE TITLE
Bug in animated Number

### ISSUE THREAD

**Issue by sdabbo** [creativetimofficial/ct-vue-now-ui-dashboard-pro#28]
Animated numbers, unfortunately, do not work. They animate the first time when loading the page, but when the corresponding variable changes it does not animate to the new number but rather just displays the old one.

I fixed this by renaming the function in the **AnimatedNumber** components watch from _number_ to _value_ as that is also how the variable is called.

**Comment by cristijora** [comment]
Thanks for the notice @sdabbo 
Just fixed that in the code as well

**Comment by cristijora** [comment]
Should be fixed in 1.2.0
