### ISSUE TITLE
[Bug] npm ERR! ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by cod3gen** [creativetimofficial/ct-vue-now-ui-dashboard-pro#37]
### Version
2.1.0
### Reproduction link
https://www.google.com
### Operating System
Windows 10
### Device
PC
### Browser & Version
X
### Steps to reproduce
Download latest version of "Vue Now UI Dashboard PRO" on your websites, unpack and go to folder -> run npm install.

### What is expected?
All packages installed and ready.
### What is actually happening?
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\Projects\Genaudio DSP Web\vue-now-ui-dashboard-pro-v2.1.0\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\xx\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\xx\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 14ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 712ms
29 timing idealTree:userRequests Completed in 0ms
30 silly idealTree buildDeps
31 silly fetch manifest vee-validate@4.1.2
32 timing arborist:ctor Completed in 1ms
33 http fetch GET 200 https://registry.npmjs.org/vee-validate 723ms (cache revalidated)
34 silly fetch manifest vue@3.0.11
35 http fetch GET 200 https://registry.npmjs.org/vue 49ms (cache revalidated)
36 silly fetch manifest vue-router@4.0.1
37 http fetch GET 200 https://registry.npmjs.org/vue-router 47ms (cache revalidated)
38 silly fetch manifest vue-toastification@2.0.0-beta.9
39 http fetch GET 200 https://registry.npmjs.org/vue-toastification 804ms (cache revalidated)
40 silly fetch manifest @vue/cli-plugin-eslint@4.5.15
41 http fetch GET 200 https://registry.npmjs.org/@vue%2fcli-plugin-eslint 67ms (cache revalidated)
42 silly fetch manifest @vue/cli-service@4.5.15
43 http fetch GET 200 https://registry.npmjs.org/@vue%2fcli-service 75ms (cache revalidated)
44 silly fetch manifest @vue/compiler-sfc@3.0.11
45 http fetch GET 200 https://registry.npmjs.org/@vue%2fcompiler-sfc 142ms (cache revalidated)
46 silly fetch manifest vue-template-compiler@^2.0.0
47 http fetch GET 200 https://registry.npmjs.org/vue-template-compiler 805ms (cache revalidated)
48 silly fetch manifest eslint@7.32.0
49 http fetch GET 200 https://registry.npmjs.org/eslint 49ms (cache revalidated)
50 silly fetch manifest eslint@>= 1.6.0 < 7.0.0
51 timing idealTree Completed in 3516ms
52 timing command:install Completed in 3529ms
53 verbose stack Error: unable to resolve dependency tree
53 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1356:25)
53 verbose stack     at Arborist.[loadPeerSet] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1322:34)
53 verbose stack     at async Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:930:11)
53 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:216:7)
53 verbose stack     at async Promise.all (index 1)
53 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:149:5)
53 verbose stack     at async Install.install (C:\Program Files\nodejs\node_modules\npm\lib\install.js:170:5)
54 verbose cwd D:\Projects\Genaudio DSP Web\vue-now-ui-dashboard-pro-v2.1.0
55 verbose Windows_NT 10.0.19044
56 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
57 verbose node v16.13.2
58 verbose npm  v8.1.2
59 error code ERESOLVE
60 error ERESOLVE unable to resolve dependency tree
61 error
62 error While resolving: [1mvue-now-ui-dashboard-pro[22m@[1m2.1.0[22m
62 error Found: [1meslint[22m@[1m7.32.0[22m[2m[22m
62 error [2mnode_modules/eslint[22m
62 error   [33mdev[39m [1meslint[22m@"[1m7.32.0[22m" from the root project
62 error
62 error Could not resolve dependency:
62 error [35mpeer[39m [1meslint[22m@"[1m>= 1.6.0 < 7.0.0[22m" from [1m@vue/cli-plugin-eslint[22m@[1m4.5.15[22m[2m[22m
62 error [2mnode_modules/@vue/cli-plugin-eslint[22m
62 error   [33mdev[39m [1m@vue/cli-plugin-eslint[22m@"[1m4.5.15[22m" from the root project
62 error
62 error Fix the upstream dependency conflict, or retry
62 error this command with --force, or --legacy-peer-deps
62 error to accept an incorrect (and potentially broken) dependency resolution.
62 error
62 error See C:\Users\xx\AppData\Local\npm-cache\eresolve-report.txt for a full report.
63 verbose exit 1

---

**Comment by dragosct10** [comment]
Hi, @cod3gen! Thanks for using our products and sorry for the late response. We will give it a test and we will come with answer asap. 

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi! To make it work you need to:  
1. Go in package.json file and replace node-sass dependence with ` "sass": "1.49.0"`, then  run `npm install ----legacy-peer-deps`.

2. Now please run these 2 commands:` npm install -g sass-migrator` and `sass-migrator division **/*.scss`. 

3. Go and search in assets/scss/now-ui-dashboard/element-ui-plugins/_tags.scss for `@include tag('info', $info-color)` and add to all includes ` ; ` at the end line, also go to assets/scss/now-ui-dashboard/element-ui-plugins/_select.scss and search for `@include select('info')` and add to all includes ` ; `. 

Now the product should run properly!

Regards,
Dragos

**Comment by cod3gen** [comment]
Hi @dragosct10,

Thank you for your reply. Running with legacy peer deps works and i can install now, but this opens for next issue when trying to run the app:

> vue-now-ui-dashboard-pro-v2.1.0>npm run serve
> > vue-now-ui-dashboard-pro@2.1.0 serve
> > vue-cli-service serve --open
> 
>  INFO  Starting development server...
>  ERROR  Error: Cannot find module 'webpack'
> Require stack:
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\webpack-dev-server\lib\Server.js
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\@vue\cli-service\lib\commands\serve.js
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\@vue\cli-service\lib\Service.js
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\@vue\cli-service\bin\vue-cli-service.js
> Error: Cannot find module 'webpack'
> Require stack:
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\webpack-dev-server\lib\Server.js
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\@vue\cli-service\lib\commands\serve.js
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\@vue\cli-service\lib\Service.js
> - vue-now-ui-dashboard-pro-v2.1.0\node_modules\@vue\cli-service\bin\vue-cli-service.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (vue-now-ui-dashboard-pro-v2.1.0\node_modules\webpack-dev-server\lib\Server.js:23:17)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)

**Comment by dragosct10** [comment]
Did you delete first the `node_modules` and `package-lock.json` ?

Regards,
Dragos
