### ISSUE TITLE
syntax error on routes

### ISSUE THREAD

**Issue by ekuzu** [creativetimofficial/ct-vue-now-ui-dashboard-pro#6]
ERROR  Failed to compile with 1 errors                                                                                                                                           11:56:54

 error  in ./src/routes/routes.js

Syntax Error:
  15 |
  16 | // Pages
> 17 | const User = ()=>  import('src/pages/Dashboard/Pages/UserProfile.vue');
     |                    ^
  18 | const Pricing = ()=>  import('src/pages/Dashboard/Pages/Pricing.vue');
  19 | const TimeLine = ()=>  import('src/pages/Dashboard/Pages/TimeLinePage.vue');
  20 | const Login = ()=>  import('src/pages/Dashboard/Pages/Login.vue');

**Comment by cristijora** [comment]
Hi Enric. Will paste the email response here. Please make sure you have .babelrc file inside the project. Many people use mac and when they copy stuff from the archive they miss the .babelrc file since its hidden on mac by default. If that's not the issue, please let me know.

**Comment by gamcoh** [comment]
Hi i have the same issue despite the fact that i do have the babelrc file at the root of my project.

The error is: 
`[eslint] Parsing error: unexpected token import`

**Comment by cristijora** [comment]
@gamcoh can you show the full error for this case ?

**Comment by gamcoh** [comment]
routes.js
`[eslint] Parsing error: Unexpected token import`

but i think this error is generated by my code editor (VS code) because i don't get the error when the code compile or in the navigator console.

**Comment by cristijora** [comment]
A common problem for MAC users is that because of hidden files, `.bablerc` file is not copied from the archive. If everything works, but you have a linting error, most likely it's due to the editor. If the problem persists, feel free to reopen the issue
