### ISSUE TITLE
 error  in ./src/components/Inputs/formGroupInput.vue

### ISSUE THREAD

**Issue by ekuzu** [creativetimofficial/ct-vue-now-ui-dashboard-pro#7]
ERROR  Failed to compile with 2 errors                                                                                                                                           13:52:31

 error  in ./src/components/Inputs/formGroupInput.vue

Syntax Error:
  65 |     listeners() {
  66 |       return {
> 67 |         ...this.$listeners,
     |         ^
  68 |         input: this.updateValue,
  69 |         focus: this.onFocus,
  70 |         blur: this.onBlur

**Comment by cristijora** [comment]
Hi @ekuzu Please see my email response and the response from the other issue. Hope you solve the problem quickly

**Comment by dlight20** [comment]
Hi @cristijora I am having the same issue - can you please send me the solution you sent above?

**Comment by pcollaog** [comment]
Same issue here... can you help me?

**Comment by cristijora** [comment]
This issue should no longer be present in the latest update.
To get the update, go to your accounts (Download section) and re-download the template, copy the `assets, components` and `vue.config.js` files. Also you could diff `package.json` to check what packages were upgraded.
