### ISSUE TITLE
Menu items unreachable at the bottom of the sidebar

### ISSUE THREAD

**Issue by sylvaincaillot** [creativetimofficial/ct-vue-now-ui-dashboard-pro#8]
Hello,

If you go to https://timcreative.github.io/vue-now-ui-dashboard-pro and you start expanding the Tables and the Components menu items, you have menu items at the bottom of the sidebar menu which become unreachable...
You need to collapse some of the menu items to see them again. It seems to be a common issue for the 3 templates.
One solution would be to collapse non-related menu items when you click on one item

Cheers

S.

**Comment by cristijora** [comment]
Hi @sylvaincaillot There should be a vertical scroll in the sidebar. Doesn't it work for you ?

Would be great if you can share on what operating system and browser this happens so we could test it out.

**Comment by sylvaincaillot** [comment]
OK, the vertical scroll appears when you start scrolling down with the mouse, not when you just expand the menu items and that the menu items at the bottom get hidden. Just need to get use to this navigation pattern.
